pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
       
        stage("maven") {
            steps{
            sh 'mvn clean validate compile install test package'
        }
    }
}
}